"""Generate AeroSpace TOML config for fleet-up workspaces."""

from pathlib import Path

AEROSPACE_CONFIG_PATH = Path.home() / ".aerospace.toml"


def generate_aerospace_toml(num_workspaces: int = 4, gap: int = 8) -> str:
    """Generate an AeroSpace config with fleet-up workspaces."""
    lines = [
        "# Generated by fleet-up — do not edit manually",
        "# Regenerate with: fleet-up --gen-aerospace",
        "",
        "after-login-command = []",
        "after-startup-command = []",
        "start-at-login = true",
        "",
        "[gaps]",
        f"inner.horizontal = {gap}",
        f"inner.vertical = {gap}",
        f"outer.left = {gap}",
        f"outer.right = {gap}",
        f"outer.top = {gap}",
        f"outer.bottom = {gap}",
        "",
        "[mode.main.binding]",
    ]

    # Workspace focus: alt-N
    for i in range(1, num_workspaces + 1):
        lines.append(f"alt-{i} = 'workspace {i}'")

    lines.append("")

    # Move to workspace: alt-shift-N
    for i in range(1, num_workspaces + 1):
        lines.append(f"alt-shift-{i} = 'move-node-to-workspace {i}'")

    lines.append("")

    # Navigation
    lines.extend([
        "# Focus navigation",
        "alt-h = 'focus left'",
        "alt-j = 'focus down'",
        "alt-k = 'focus up'",
        "alt-l = 'focus right'",
        "",
        "# Move windows",
        "alt-shift-h = 'move left'",
        "alt-shift-j = 'move down'",
        "alt-shift-k = 'move up'",
        "alt-shift-l = 'move right'",
        "",
        "# Layout",
        "alt-slash = 'layout tiles horizontal vertical'",
        "alt-comma = 'layout accordion horizontal vertical'",
        "alt-f = 'fullscreen'",
        "",
        "# Resize",
        "alt-shift-minus = 'resize smart -50'",
        "alt-shift-equal = 'resize smart +50'",
    ])

    return "\n".join(lines) + "\n"


def write_aerospace_config(num_workspaces: int = 4, gap: int = 8,
                           path: Path = AEROSPACE_CONFIG_PATH) -> Path:
    """Write AeroSpace config to disk. Returns the path written."""
    content = generate_aerospace_toml(num_workspaces, gap)
    path.write_text(content)
    return path
